apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
        - name: ocelot-api-gateway
          image: docker.io/library/ocelot-api-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: JWT_SigningKey
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_SigningKey
            - name: JWT_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_AUTHORITY
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_AUDIENCE
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway
spec:
  selector:
    app: ocelot-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
